let LAST_EXPORT={dataUrl:null,blob:null,filename:"comunicado.png"};
function downloadTextFile(filename,content,type){const blob=new Blob([content],{type}); const url=URL.createObjectURL(blob); const link=document.createElement("a"); link.href=url; link.download=filename; link.click(); URL.revokeObjectURL(url);}
function downloadGeneratedHTML(){downloadTextFile("comunicado_generado.html",document.documentElement.outerHTML,"text/html;charset=utf-8");}
async function renderPNGBlob(template){await document.fonts.ready; await new Promise(r=>setTimeout(r,180)); const original=document.getElementById("artboard"); const artboard=original.cloneNode(true); const width=template.width; const height=Math.ceil(parseFloat(getComputedStyle(original).height)); artboard.setAttribute("xmlns","http://www.w3.org/1999/xhtml"); artboard.style.width=`${width}px`; artboard.style.height=`${height}px`; artboard.style.transform="none"; artboard.style.position="relative"; artboard.style.overflow="hidden"; artboard.style.background="#ffffff"; const serialized=new XMLSerializer().serializeToString(artboard); const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><foreignObject width="${width}" height="${height}">${serialized}</foreignObject></svg>`; const svgBlob=new Blob([svg],{type:"image/svg+xml;charset=utf-8"}); const url=URL.createObjectURL(svgBlob); try{const image=await new Promise((resolve,reject)=>{const img=new Image(); img.onload=()=>resolve(img); img.onerror=reject; img.src=url;}); const canvas=document.createElement("canvas"); canvas.width=width; canvas.height=height; const ctx=canvas.getContext("2d"); ctx.fillStyle="#ffffff"; ctx.fillRect(0,0,width,height); ctx.drawImage(image,0,0); return await new Promise(resolve=>canvas.toBlob(resolve,"image/png"));}finally{URL.revokeObjectURL(url);}}
function blobToDataURL(blob){return new Promise(resolve=>{const reader=new FileReader(); reader.onload=()=>resolve(reader.result); reader.readAsDataURL(blob);});}
async function generateImagePreview(template){const blob=await renderPNGBlob(template); if(!blob){alert("No se pudo generar la imagen en este navegador."); return;} const dataUrl=await blobToDataURL(blob); LAST_EXPORT={dataUrl,blob,filename:"comunicado.png"}; const wrap=document.getElementById("exportImageWrap"); wrap.innerHTML=""; const img=document.createElement("img"); img.src=dataUrl; img.alt="Comunicado generado"; wrap.appendChild(img); document.getElementById("exportModal").hidden=false;}
function closeExportModal(){document.getElementById("exportModal").hidden=true;}
function downloadLastImage(){if(!LAST_EXPORT.dataUrl){alert("Primero genera la imagen."); return;} const link=document.createElement("a"); link.href=LAST_EXPORT.dataUrl; link.download=LAST_EXPORT.filename; link.click();}
function openLastImage(){if(!LAST_EXPORT.dataUrl){alert("Primero genera la imagen."); return;} const win=window.open(); if(win){win.document.write(`<img src="${LAST_EXPORT.dataUrl}" style="max-width:100%;height:auto;">`); win.document.close();}else{window.location.href=LAST_EXPORT.dataUrl;}}
async function shareLastImage(){if(!LAST_EXPORT.blob){alert("Primero genera la imagen."); return;} const file=new File([LAST_EXPORT.blob],LAST_EXPORT.filename,{type:"image/png"}); if(navigator.canShare&&navigator.canShare({files:[file]})&&navigator.share){try{await navigator.share({files:[file],title:"Comunicado",text:"Imagen generada"});}catch(e){}}else if(navigator.share){try{await navigator.share({title:"Comunicado",text:"Imagen generada",url:LAST_EXPORT.dataUrl});}catch(e){}}else{alert("Este navegador no permite compartir archivos directamente. Mantén presionada la imagen y guárdala.");}}
async function downloadGeneratedPNG(template){await generateImagePreview(template);}
document.addEventListener("DOMContentLoaded",()=>{const closeBtn=document.getElementById("closeExportModal"),downloadBtn=document.getElementById("downloadImageBtn"),openBtn=document.getElementById("openImageBtn"),shareBtn=document.getElementById("shareImageBtn"); if(closeBtn)closeBtn.addEventListener("click",closeExportModal); if(downloadBtn)downloadBtn.addEventListener("click",downloadLastImage); if(openBtn)openBtn.addEventListener("click",openLastImage); if(shareBtn)shareBtn.addEventListener("click",shareLastImage);});
