const CACHE_NAME='daedalus-v14-2-responsive-20260806';
const APP_SHELL=[
  "./ESTRUCTURA_V12.txt",
  "./LEEME_PRIMERO.txt",
  "./LEEME_V13.txt",
  "./LEEME_V14_1.txt",
  "./LEEME_V14_CONDOLENCIAS.txt",
  "./assets/fonts/Montserrat-Bold.otf",
  "./assets/fonts/Montserrat-ExtraBold.otf",
  "./assets/fonts/Montserrat-Regular.otf",
  "./assets/fonts/Raleway-Black.otf",
  "./assets/fonts/Raleway-ExtraBold.otf",
  "./assets/fonts/Raleway-Regular.otf",
  "./assets/icons/apple-touch-icon.png",
  "./assets/icons/daedalus.svg",
  "./assets/icons/icon-192.png",
  "./assets/icons/icon-512.png",
  "./assets/logo-fge.svg",
  "./assets/marcas/AAA.png",
  "./assets/marcas/README_BIBLIOTECA.txt",
  "./assets/marcas/amistad.png",
  "./assets/marcas/blanqueo-jr.png",
  "./assets/marcas/catalogo.json",
  "./assets/marcas/celu.png",
  "./assets/marcas/en-familia.png",
  "./assets/marcas/euro2024.png",
  "./assets/marcas/metastasis.png",
  "./assets/marcas/pampa.png",
  "./assets/marcas/plaga.png",
  "./assets/marcas/purga.png",
  "./assets/templates/condolencias-base.svg",
  "./assets/templates/fge-comunicado.svg",
  "./assets/vendor/jszip.min.js",
  "./comunicado.html",
  "./condolencias.html",
  "./config.json",
  "./css/fonts.css",
  "./css/styles.css",
  "./index.html",
  "./js/app.js",
  "./js/condolencias.js",
  "./js/core/engine.js",
  "./js/core/parser.js",
  "./js/core/templateStore.js",
  "./js/exporters/exporter.js",
  "./manifest.webmanifest",
  "./titulares.html",
  "./version.json"
];
self.addEventListener('install',event=>{
  event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_SHELL)));
  self.skipWaiting();
});
self.addEventListener('activate',event=>{
  event.waitUntil(caches.keys().then(keys=>Promise.all(
    keys.filter(key=>key!==CACHE_NAME).map(key=>caches.delete(key))
  )));
  self.clients.claim();
});
self.addEventListener('fetch',event=>{
  if(event.request.method!=='GET')return;
  const url=new URL(event.request.url);
  if(url.origin!==location.origin)return;
  event.respondWith(
    fetch(event.request)
      .then(response=>{
        const copy=response.clone();
        caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy));
        return response;
      })
      .catch(()=>caches.match(event.request))
  );
});
