const DaedalusExporter=(()=>{let last={dataUrl:null,blob:null,filename:"comunicado.png"};const status=t=>{const e=document.getElementById("exportStatus");if(e)e.textContent=t||""},modal=()=>document.getElementById("exportModal").hidden=false,close=()=>document.getElementById("exportModal").hidden=true;
async function ready(){await document.fonts.ready;await new Promise(r=>setTimeout(r,200))}
async function htmlToImageBlob(node,t){if(!window.htmlToImage)throw new Error("html-to-image no cargó");return await htmlToImage.toBlob(node,{width:t.width,height:Math.ceil(parseFloat(getComputedStyle(node).height)),cacheBust:true,backgroundColor:"#ffffff",pixelRatio:2,style:{transform:"none",transformOrigin:"top left"}})}
async function fallbackBlob(node,t){const a=node.cloneNode(true),w=t.width,h=Math.ceil(parseFloat(getComputedStyle(node).height));a.setAttribute("xmlns","http://www.w3.org/1999/xhtml");a.style.width=`${w}px`;a.style.height=`${h}px`;a.style.transform="none";a.style.position="relative";a.style.overflow="hidden";a.style.background="#fff";const s=new XMLSerializer().serializeToString(a),svg=`<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}"><foreignObject width="${w}" height="${h}">${s}</foreignObject></svg>`,u=URL.createObjectURL(new Blob([svg],{type:"image/svg+xml;charset=utf-8"}));try{const img=await new Promise((res,rej)=>{const i=new Image();i.onload=()=>res(i);i.onerror=rej;i.src=u});const c=document.createElement("canvas");c.width=w;c.height=h;const x=c.getContext("2d");x.fillStyle="#fff";x.fillRect(0,0,w,h);x.drawImage(img,0,0);return await new Promise(r=>c.toBlob(r,"image/png"))}finally{URL.revokeObjectURL(u)}}
function blobToDataURL(b){return new Promise(r=>{const fr=new FileReader();fr.onload=()=>r(fr.result);fr.readAsDataURL(b)})}
async function generatePNG(t){modal();status("Generando imagen...");document.getElementById("exportImageWrap").innerHTML="";await ready();const node=document.getElementById("artboard");let blob=null;try{blob=await htmlToImageBlob(node,t)}catch(e){console.warn(e);try{blob=await fallbackBlob(node,t)}catch(err){console.error(err);status("No se pudo generar la imagen.");return}}if(!blob){status("No se pudo generar la imagen.");return}const dataUrl=await blobToDataURL(blob);last={dataUrl,blob,filename:"comunicado.png"};const img=document.createElement("img");img.src=dataUrl;img.alt="Imagen generada";document.getElementById("exportImageWrap").appendChild(img);status("Imagen lista.")}
function download(){if(!last.dataUrl){status("Primero genera la imagen.");return}const a=document.createElement("a");a.href=last.dataUrl;a.download=last.filename;a.click()}
function openImage(){if(!last.dataUrl){status("Primero genera la imagen.");return}const w=window.open();if(w){w.document.write(`<img src="${last.dataUrl}" style="max-width:100%;height:auto;">`);w.document.close()}else location.href=last.dataUrl}
async function share(){if(!last.blob){status("Primero genera la imagen.");return}const f=new File([last.blob],last.filename,{type:"image/png"});if(navigator.canShare&&navigator.canShare({files:[f]})&&navigator.share){try{await navigator.share({files:[f],title:"Imagen generada",text:"Imagen generada"})}catch(e){}}else if(navigator.share){try{await navigator.share({title:"Imagen generada",text:"Imagen generada",url:last.dataUrl})}catch(e){}}else status("Este navegador no permite compartir. Usa Abrir imagen o mantén presionada la vista previa.")}
function downloadHTML(){const b=new Blob([document.documentElement.outerHTML],{type:"text/html;charset=utf-8"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="comunicado_generado.html";a.click();URL.revokeObjectURL(u)}
function bind(){document.getElementById("closeExportModal")?.addEventListener("click",close);document.getElementById("downloadImageBtn")?.addEventListener("click",download);document.getElementById("openImageBtn")?.addEventListener("click",openImage);document.getElementById("shareImageBtn")?.addEventListener("click",share)}
return{generatePNG,downloadHTML,bind}})();document.addEventListener("DOMContentLoaded",DaedalusExporter.bind);
